# Site settings
title: Docs
email: developer@ezetap.com
description: Home pate for Ezetap SDK documentation
baseurl: "/docs" # the subpath of your site, e.g. /blog/
url: "http://www.ezetap.com" # the base hostname & protocol for your site

# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown


page_types:
  - User Docs
  - Client SDK
  - Server API

home_category: home